# Package Overview
package_name: classification_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (sale price)
target: Survived

pipeline_name: classification_model
pipeline_save_file: class_model_output_v

# Will cause syntax errors since they begin with numbers
# nested dictionary
variables_to_rename:
  Novariables: Novariables
  

# Intendention matters in yml and here a key with intended dash is the list 
features:
  - sibsp
  - parch
  - embarked
  - title
  - cabin
  - age
  - fare
  - pclass
  - sex
  

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

alpha: 0.0005

# categorical variables with NA in train set
categorical_vars_with_na_missing:
  - cabin
  - embarked

numerical_vars_with_na:
  - age
  - fare

var_handled_imputation:
  - cabin

categorical_vars:
  - pclass
  - sex
  - sibsp
  - parch
  - embarked
  - title
  - cabin